
site_name: Cristian Sulea
site_description: Senior Java Developer (& Software Architect), PSS Prosoft Solutions, February 2008 - Present, Bucharest, Romania
site_url: https://cristian.sulea.net
site_author: Cristian Sulea

nav:
    - Knowledge Base: blog/
    - Projects: projects/

theme:
    name: spacelab
    custom_dir: customization/
